version: '3.8'

services:
  postgres:
    container_name: resourcehub-db
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=resourcehub
